apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  creationTimestamp: "2024-05-12T09:02:29Z"
  generation: 7
  labels:
    app: spring-petclinic-rest-rec
  name: spring-petclinic-rest-rec
  namespace: default
  resourceVersion: "3429"
  uid: 7950121f-5c34-4ef5-a661-81872d6e35cb
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spring-petclinic-rest-rec
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-petclinic-rest-rec
    spec:
      containers:
      - image: docker.io/springcommunity/spring-petclinic-rest:3.2.1
        imagePullPolicy: IfNotPresent
        name: spring-petclinic-rest
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2024-05-12T09:02:29Z"
    lastUpdateTime: "2024-05-12T09:53:02Z"
    message: ReplicaSet "spring-petclinic-rest-rec-77d4cd968d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-05-12T09:53:50Z"
    lastUpdateTime: "2024-05-12T09:53:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 7
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
