apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-12T07:41:30Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4441"
  uid: 2ac52e4d-a4df-49e3-a4b0-5be832d5335f
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.105.106
  clusterIPs:
  - 10.100.105.106
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31622
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
